-- Deploy appschema
-- requires: roles

BEGIN;

CREATE SCHEMA "1";
GRANT USAGE ON SCHEMA "1" TO c11z;
GRANT USAGE ON SCHEMA "1" TO anon;
GRANT USAGE ON SCHEMA "1" TO lurker;
GRANT USAGE ON SCHEMA "1" TO api;

COMMIT;
