-- Revert upsert_strip

BEGIN;

DROP FUNCTION cg.upsert_strip(UUID, VARCHAR, INTEGER, VARCHAR, VARCHAR, VARCHAR, VARCHAR, TEXT);
DROP FUNCTION cg.upsert_strip(UUID, UUID, VARCHAR, INTEGER, VARCHAR, VARCHAR, VARCHAR, VARCHAR, TEXT);

COMMIT;
