-- Revert upsert_strip

BEGIN;

DROP FUNCTION "1".upsert_strip(UUID, VARCHAR, INTEGER, VARCHAR, VARCHAR, VARCHAR, VARCHAR, TEXT);
DROP FUNCTION "1".upsert_strip(UUID, UUID, VARCHAR, INTEGER, VARCHAR, VARCHAR, VARCHAR, VARCHAR, TEXT);

COMMIT;
